[theme]
primaryColor="#6366F1"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FAFAFA"
textColor="#1F2937"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=true

[browser]
gatherUsageStats = false 